[package]
name = "game-input"
version.workspace = true
edition.workspace = true

[dependencies]
game-types.workspace = true
bevy = { version = "0.17", default-features = false, features = ["bevy_state"] }
gilrs = "0.11"
tracing = "0.1"
