[package]
name = "network"
version.workspace = true
edition.workspace = true

[lib]
name = "network"
path = "src/lib.rs"

[dependencies]
async-std = "1.13"
futures-lite = "2.6"
md5 = "0.8"
packets.workspace = true
